### ISSUE TITLE
Properly exit the EventMachine run loop

### ISSUE THREAD

**Issue by bhouse** [bhouse/lita-flowdock#3]
Right now the `EventMachine.run` loop is being closed on shutdown by calling `source.close` from outside the loop

https://github.com/bhouse/lita-flowdock/blob/master/lib/lita/adapters/flowdock.rb#L27-L35
https://github.com/bhouse/lita-flowdock/blob/master/lib/lita/adapters/flowdock/connector.rb#L56-L58

This triggers a `RuntimeError`, which is currently being rescued:

``` shell
[2015-02-08 05:42:18 UTC] INFO: Connected to flowdock streaming API
^C[2015-02-08 05:42:21 UTC] ERROR: "Connection lost. Reconnecting."
/vagrant/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.6/lib/em/connection.rb:266:in `close_connection': eventmachine not initialized: evma_close_connection (RuntimeError)
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.6/lib/em/connection.rb:266:in `close_connection'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:198:in `unbind'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/em-eventsource-0.2.0/lib/em-eventsource.rb:107:in `close'
    from /vagrant/lita-flowdock/lib/lita/adapters/flowdock/connector.rb:57:in `shut_down'
    from /vagrant/lita-flowdock/lib/lita/adapters/flowdock.rb:34:in `shut_down'
    from /vagrant/lita-flowdock/lib/lita/adapters/flowdock.rb:29:in `rescue in run'
    from /vagrant/lita-flowdock/lib/lita/adapters/flowdock.rb:19:in `run'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/lita-4.2.0/lib/lita/robot.rb:69:in `run'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/lita-4.2.0/lib/lita.rb:79:in `run'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/lita-4.2.0/lib/lita/cli.rb:77:in `start'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /vagrant/vendor/bundle/ruby/2.1.0/gems/lita-4.2.0/bin/lita:6:in `<top (required)>'
    from /vagrant/vendor/bundle/ruby/2.1.0/bin/lita:23:in `load'
    from /vagrant/vendor/bundle/ruby/2.1.0/bin/lita:23:in `<main>'
```

**Comment by jimmycuadra** [comment]
`EM.stop` will shut down the reactor, but it will also raise an exception if called when the reactor isn't running, so you'll want to guard it with `EM.reactor_running?`. See [Lita::Adapters::Slack::RTMConnection#shut_down](https://github.com/kenjij/lita-slack/blob/b27046fb13bbe59fc31ad27d0fdf16b63077f712/lib/lita/adapters/slack/rtm_connection.rb#L63).
